# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cases',
                'doc_host': 'https://scmopt.github.io',
                'git_url': 'https://github.com/scmopt/cases',
                'lib_path': 'cases'},
  'syms': {'cases.core': {'cases.core.foo': ('core.html#foo', 'cases/core.py')}}}
